### ISSUE TITLE
Add new document for "bulk" external resources

### ISSUE THREAD

**Issue by tacaswell** [bluesky/event-model#219]
Currently the implementation of external data is limited to filling in data on a per-event per-field basis, basically the smallest quanta of data that the system can express.  While this works extremely well for something like image stacks of equal length, this works very poorly in cases where the data is natively ragged (single-photon detectors) or when there are many many relatively small data sets (e.g. scanned florescence data).  The difficulties vary from fully breaking the ability to put the data in an xarray to pathological performance problems.

One way out of this is to expand what can be "external".

## option A:

Expand the notion of "external" to be able to replace all of the rows in a field in a stream at once.   This would help significantly in cases like scanned florescence (because we can read out all of the data en-masse), but it would make it much much harder to pull out a _single_ events worth of data (but not impossible).   You could imagine saying "these col_datum is for index N -> N+m" so you get chunk level access.  A wrinkle that this is going to have is that we have the ability to emit multiple events with the same event number and we will silently ignore all but the last one (so if you re-take points it "does the right thing" 😱 .  This probably was a poor choice,but it made sense at the time).

The splicing to merge these into tiled is probably do-able.  We already do the splicing on a per-row basis and tiled already has a deep sense of chunking.  You would still keep the rule that the `col_datum` would have to go out before any event that refers to it goes out would still hold and I guess we would just duplicate the same `col_datum_uid` in all of the events.

A pro of this plan is that we can still use the structure of the `Events` to do the association between the "big" data and the "small" data and collate between multiple data sources in a very structural way.   That is, an `Event` that says "I have a motor position, an image, and a spectrum that are all 'at the same time for science'" is is much more powerful statement than "there are 3 streams in this Run (good luck guessing the names!) that _should_ be the same length and you can zip them...good luck!" in the same way that saying "this is a data frame" is a more powerful statement than "this is a dict of numpy arrays that I _promise_ are all the same length".

## option B:

The same as option A, but also replace multiple fields.  Again, this would help significantly with multi-channel spectral data as we could read up the whole x, y, channel, E hyper cube up at once.  You could still get the nice chunking, as option A but maybe even better.   This has all of the complexity of the above, but now spread across columns.   Also has the same pros.

At some point, this turns into an implementation of panda's block manager.

## option C:

Scale the notion up to be "the entire stream".

This gets around all of the splicing related issues (because it is everything).  This will handle cases like where we have some detector/device that outputs table like data in large volumes.  If we had an analogy of `stream_reosource` and maybe `stream_datum` (you could say "it is the whole stream, you'll only ever have one datum so stuff everything in the resource", but I think this is wrong as you may have a detector that writes an un-known number of fixed sized files.  It is better to positively say "and I expect another file" rather than to say "just glob all of those" because you will be able to detect when a file is missing (the document claimed it was there but you can not find it!) and resilient against the detector writing more later with the same file-prefix that is unrelated). 

This would also be very useful for single-photon detectors (where you do not know the size of the output until (well) after the fact) and complicated flyscans that may be already writing data out to (multiple) files.

A down side of this approach is that we would lose the ability to associate the rows with an event an another stream via indexing (but other methods like time stamping or including an "event index column" would still work.   The later may be the best approach to dealing with "ragged" data anyway.

## option D

Option C but provide a bunch of streams.

The down side of this is that it is a bunch of extra book keeping / semantics, but an upside would be that complicated files can provide mulitple streams and we will be able to open them only once.

-----

I think we should implement option D and maybe B, but do D first.   B has the possibility of providing some big speed improvements, but I think is actually much more complex to implement.  On the other had D will provide a very good escape hatch for some problems that have come up at both BNL and as DLS is thinking about adapting / wrapping / extending malcom.

Going down the path of D we should do our best to keep "feature" parity with the current scheme so we should still get a descriptor per out-sourced stream and we should make a best-effort to include event counts in the stop document.   To make this work we would have to add two new documents `stream_resource`, `stream_datum`.  I propose the following schema:

```yaml
- stream_resource:
   - spec : str # mapping to how to read this
     root : str # the "root" part of the resource path
     resource_path : str # the rest of the resource path, may want to call this 'uri'?
     path_semantics : {unix | windows}  # \ vs / maybe, maybe not? 
     uid : str # a uuid
     run_start : str  # mapping to the run start this belongs to
     stream_names : List[str]   # list of the stream names this provides
     resource_kwargs : Dict[str, Any]  # anything to pass into the handler
- stream_datum
   - resource_id : str refernce back to the stream_resource
     uid : a uuid
     stream_name : str # the same of the stream this is providing a block of
     block_id : int   # the order in the stream of this block
     datum_kwargs : Dict[str, Any]  # what to pass to call the handler with
     event_offset : int # what is the sequence number of the first event in this block
```

and signatures:

```python
class StreamHandler:
    def __init__(self, uri_path: str, **resource_kwargs):
        ...

    def get_block(self, stream_name: str, block_id: int, **datum_kwargs):
        ...

```

The order rules would be descriptor must come before a stream_resource, stream_resource must come before a stream_datum.  I think we should prohibit emitting more than one descriptor if using external streams (because otherwise spelling at what point to change descriptors gets too hard).   You can have as many stream_resource describing a stream as you want and each stream_resource can be referred to by as many stream_datum as you want, but `block_id` must be a unique run of integers with no gaps and be emitted in order.    event_offset must be unique and increasing, but can (obviously) have gaps.
